[connections.snowflake]
account = "DCLIHHD.JWA53285"
user = "MonishaQ4"
password = "newTalend33#"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
